<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Review extends Model
{
    protected $fillable = [
        'name', 'email', 'rate', 'body', 'product_id'
    ];

    public static function boot()
    {
        static::created(function ($review) {
            if(User::where('email', $review->email)->exists()){
                $review->public = 'Member';
            }else{
                $review->public = 'Anymous';
            }
            $review->save();
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function product()
    {
        return $this->belongsTo(Product::class);
    }
}
